#! /usr/bin/env ruby
#
# Copy the file from the drafts folder, add the current date, and update the
# filename.  Remove any commented out lines from the front matter.

require 'yaml'

now = Time.now
draft = File.basename(ARGV[0], '.md')
draft_filename = File.join('content/post/', "_#{draft}.md")
post_filename = File.join('content/post/', "#{draft}.md")

draft_contents = File.read(draft_filename)

# Split the contents into the YAML front matter and the content
md = draft_contents.match(/^(?<metadata>---\s*\n.*?\n?)^(---\s*$\n?)/m)
contents = md.post_match
frontmatter = YAML.safe_load(md[:metadata])

modifications = {
  'draft' => false,
  'date' => now.strftime('%Y-%m-%dT%H:%M:%S%:z'),
  'slug' => draft,
}

File.open(post_filename, 'w') do |post|
  post.puts frontmatter.merge(modifications).to_yaml
  post.puts "---\n"
  post.puts contents
end

File.unlink(draft_filename) if File.exist?(post_filename)
puts "Published #{post_filename}"
